# Generated by Django 5.0.6 on 2024-07-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=91, max_length=20),
            preserve_default=False,
        ),
    ]
