# Generated by Django 5.0.6 on 2025-03-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='description',
            new_name='category',
        ),
    ]
